### ISSUE TITLE
Material View

### ISSUE THREAD

**Issue by 2martens** [frmwrk123/oeprint#3]
# Specification

The Material View has two components:
- list of all materials (with hierarchy)
- detail view for a selected material

The list shows all materials ordered by alphabet in ascending order (default) with a checkbox in front of every material. There is a checkbox for all materials at the top to select all materials at once. Furthermore if a material is checked all sub-materials are also checked.
In addition there is a counter in front of each material name that specifies how often this particular material should be printed.

On the detail view you can see the specific information about that material:
- name
- filename
- page(s) of the file

This information cannot be changed in the client. It is provided with a config file which is downloaded from the server.
# Tasks
- [x] write list GUI element
- [x] write detail view GUI element
- [x] hook them up so that the detail view is updated upon a changed selection in the list
- [x] selected item counter
