### ISSUE TITLE
Configuration View

### ISSUE THREAD

**Issue by 2martens** [frmwrk123/oeprint#4]
# Specification

The Configuration View has two components:
- list of all configurations (without hierarchy)
- detail view for a selected configuration

The list shows all configurations ordered by alphabet in ascending order (default) with a checkbox in front of every configuration. There is a checkbox for all configurations at the top to select all configurations at once.

On the detail view you can see the configurations it uses. Furthermore there is a counter in front of every configuration that specifies how often this configuration should be printed. In addition you can specify how often the entire configuration should be printed.

Last but not least is the connection to the edit mode. In the detail view you can click on the Edit button which opens a new window for the editing of the configuration (see #5 ). Furthermore you can click on a New button on top of the configuration list which prompts you for the name of the new configuration. After entering the name and confirming it, the new configuration appears in the list and can be selected. Obviously it doesn't have any materials or configurations associated with it yet and must be configured by clicking on the previously mentioned Edit button.
# Tasks
- [x] write list GUI element
- [x] write detail view GUI element
- [x] hook both up with the material list to update the checked materials and their counters
