### ISSUE TITLE
Edit window

### ISSUE THREAD

**Issue by 2martens** [frmwrk123/oeprint#5]
# Specification

The edit window has three components:
- list of used configurations and materials (with print numbers) for edited configuration
- list of all available configurations
- list of all available materials

The editing itself is very simple. You can change the print numbers of the materials and configurations. Furthermore you can drag and drop between the three components. To add a configuration simply drag it onto the list of used configurations and materials. Do the same for materials. Click on the X in front of a material or configuration to remove it from the list of used materials and configurations.

After you finished editing you can use one of 3 buttons:
- save
- save as...
- close

The first button saves the work in the edited configuration. The second one prompts for a configuration name. After confirming it the changes are saved as a new configuration with that name. If there is already a configuration with that name you are asked if you want to overwrite it. Both buttons don't close the window but save the changes.

To close the window you must click on the close button. If there are unsaved changes you are asked if you really want to discard them. If not the window is not closed and you can save the changes.
# Tasks
- [ ] write used configuration and materials GUI element
- [ ] write configuration list GUI element
- [ ] write material list GUI element
